from datetime import datetime
from typing import Protocol

from tipnews.domain.models import Article, Delivery, DigestItem, Topic


class Store(Protocol):
    async def add_articles(self, articles: list[Article]) -> int: ...
    async def candidates(
        self,
        since: datetime,
        reuse_day: str | None = None,
        *,
        source_id: str | None = None,
        latest_only: bool = False,
    ) -> list[Article]: ...
    async def refresh_digest(self, day: str, items: list[DigestItem]) -> None: ...
    async def cached_summary(self, article_id: str, version: str) -> str | None: ...
    async def save_summary(self, article_id: str, summary: str, version: str) -> None: ...
    async def digest(self, day: str) -> list[DigestItem] | None: ...
    async def publish(self, day: str, items: list[DigestItem], deliver_at: int) -> None: ...
    async def subscribe(self, chat_id: int, topics: set[Topic]) -> None: ...
    async def preferences(self, chat_id: int) -> set[Topic]: ...
    async def set_active(self, chat_id: int, active: bool) -> None: ...
    async def toggle_topic(self, chat_id: int, topic: Topic) -> None: ...
    async def claim_delivery(self, now: int) -> Delivery | None: ...
    async def finish_delivery(
        self, delivery_id: int, state: str, next_attempt: int = 0
    ) -> None: ...
    async def recover_deliveries(self, today: str) -> None: ...
    async def job_due(self, name: str, now: int, interval: int) -> bool: ...
    async def cleanup(self, before: int, before_day: str) -> None: ...
